use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    End,
    Identifier,
    NumLiteral,
    StringLiteral,
    FStringLiteral,
    BytesLiteral,

    KwLet,
    KwVar,
    KwConst,
    KwFunc,
    KwGen,
    KwFriend,
    KwDo,
    KwReturn,
    KwIf,
    KwElif,
    KwElse,
    KwAnd,
    KwOr,
    KwNot,
    KwLoop,
    KwWhile,
    KwBreak,
    KwContinue,
    KwImport,
    KwUse,
    KwAs,
    KwIntern,
    KwExport,
    KwWith,
    KwMake,
    KwFor,
    KwIn,
    KwIs,
    KwThen,
    KwHandle,
    KwGo,
    KwPar,
    KwSnap,
    KwAwait,
    KwSelect,
    KwYield,
    KwSuspend,
    KwVariant,
    KwEnum,
    KwStruct,
    KwProtocol,
    KwMacro,
    KwQuote,
    KwTyped,
    KwMatch,
    KwCase,
    KwTry,
    KwCatch,
    KwThrow,
    KwDel,
    KwOutside,
    KwOverload,
    Placeholder,
    Ellipsis,

    Plus,
    Minus,
    Star,
    /// `**` — 幂运算、关键字参数展开 / `**kwargs` 形参。
    StarStar,
    Slash,
    Percent,
    Ampersand,
    Caret,
    Tilde,
    Bang,
    EqEq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    /// `<<`
    LtLt,
    /// `>>`
    GtGt,
    Comma,
    Dot,
    Colon,
    ColonEq,
    ColonColon,
    Arrow,
    FatArrow,
    Pipe,
    Bar,
    Assign,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Newline,
    /// `// ...` 行注释（`value` 为 `//` 之后的文本，不含换行）。
    LineComment,
    /// `/* ... */` 块注释（`value` 为 `/*` 与 `*/` 之间的文本）。
    BlockComment,
    Mismatch,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub value: String,
    pub line: usize,
    pub column: usize,
}

impl Token {
    pub fn new(kind: TokenKind, value: impl Into<String>, line: usize, column: usize) -> Self {
        Self {
            kind,
            value: value.into(),
            line,
            column,
        }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

pub fn keyword_or_ident(text: &str) -> TokenKind {
    match text {
        "let" => TokenKind::KwLet,
        "var" => TokenKind::KwVar,
        "const" => TokenKind::KwConst,
        "func" => TokenKind::KwFunc,
        "gen" => TokenKind::KwGen,
        "friend" => TokenKind::KwFriend,
        "do" => TokenKind::KwDo,
        "return" => TokenKind::KwReturn,
        "if" => TokenKind::KwIf,
        "elif" => TokenKind::KwElif,
        "else" => TokenKind::KwElse,
        "and" => TokenKind::KwAnd,
        "or" => TokenKind::KwOr,
        "not" => TokenKind::KwNot,
        "loop" => TokenKind::KwLoop,
        "while" => TokenKind::KwWhile,
        "break" => TokenKind::KwBreak,
        "continue" => TokenKind::KwContinue,
        "import" => TokenKind::KwImport,
        "use" => TokenKind::KwUse,
        "as" => TokenKind::KwAs,
        "intern" => TokenKind::KwIntern,
        "export" => TokenKind::KwExport,
        "with" => TokenKind::KwWith,
        "make" => TokenKind::KwMake,
        "for" => TokenKind::KwFor,
        "in" => TokenKind::KwIn,
        "is" => TokenKind::KwIs,
        "then" => TokenKind::KwThen,
        "handle" => TokenKind::KwHandle,
        "go" => TokenKind::KwGo,
        "par" => TokenKind::KwPar,
        "snap" => TokenKind::KwSnap,
        "await" => TokenKind::KwAwait,
        "select" => TokenKind::KwSelect,
        "yield" => TokenKind::KwYield,
        "suspend" => TokenKind::KwSuspend,
        "variant" => TokenKind::KwVariant,
        "enum" => TokenKind::KwEnum,
        "struct" => TokenKind::KwStruct,
        "protocol" => TokenKind::KwProtocol,
        "macro" => TokenKind::KwMacro,
        "quote" => TokenKind::KwQuote,
        "typed" => TokenKind::KwTyped,
        "match" => TokenKind::KwMatch,
        "case" => TokenKind::KwCase,
        "try" => TokenKind::KwTry,
        "catch" => TokenKind::KwCatch,
        "throw" => TokenKind::KwThrow,
        "del" => TokenKind::KwDel,
        "outside" => TokenKind::KwOutside,
        "overload" => TokenKind::KwOverload,
        _ => TokenKind::Identifier,
    }
}
