//! 静态补全目录：关键字、全局内建、`std.*`。不启动 VM。

pub const KEYWORDS: &[&str] = &[
    "let", "var", "const", "func", "gen", "friend", "do", "return", "if", "elif", "else", "and",
    "or", "not", "loop", "while", "break", "continue", "import", "use", "as", "intern", "export",
    "with", "make", "for", "in", "is", "then", "handle", "go", "par", "snap", "await", "select",
    "yield", "suspend", "variant", "enum", "struct", "protocol", "macro", "quote", "typed",
    "match", "case", "try", "catch", "throw", "del", "outside", "overload",
];

pub const BUILTINS: &[(&str, &str)] = &[
    ("true", "bool true"),
    ("false", "bool false"),
    ("none", "empty value"),
    ("print", "print(...)"),
    ("len", "len(x)"),
    ("str", "str(x)"),
    ("repr", "repr(x)"),
    ("eval", "eval(ast)"),
    ("type", "type(x)"),
    ("convert", "convert(x, T)"),
    ("is_a", "is_a(x, T)"),
    ("isinstanceof", "isinstanceof(x, T)"),
    ("hash", "hash(x)"),
    ("copy", "copy(x)"),
    ("deepcopy", "deepcopy(x)"),
    ("id", "id(x)"),
    ("iter", "iter(xs)"),
    ("next", "next(it)"),
    ("input", "input([prompt])"),
    ("int", "int(x)"),
    ("dict", "dict(...)"),
    ("rational", "rational(n[, d])"),
    ("floatstring", "floatstring(n)"),
    ("now", "now()"),
    ("gc", "gc()"),
    ("exit", "exit([code])"),
    ("help", "help(x)"),
    ("extern", "extern(...)"),
    ("std", "standard library"),
];

pub const STD_MODULES: &[&str] = &[
    "math",
    "io",
    "format",
    "iter",
    "dict",
    "ast",
    "decos",
    "typing",
    "functional",
    "collections",
    "time",
    "sync",
    "async",
    "text",
    "path",
    "fs",
    "os",
    "json",
    "test",
    "debug",
    "random",
    "re",
    "hash",
    "exceptions",
    "language",
    "http",
    "log",
    "net",
    "sqlite",
    "encoding",
    "csv",
    "toml",
    "yaml",
    "xml",
];

/// `(module, export)`。`module == ""` 表示 `std` 根上的名字。
pub const STD_EXPORTS: &[(&str, &str)] = &[
    ("math", "sin"),
    ("math", "cos"),
    ("math", "tan"),
    ("math", "asin"),
    ("math", "acos"),
    ("math", "atan"),
    ("math", "atan2"),
    ("math", "sinh"),
    ("math", "cosh"),
    ("math", "tanh"),
    ("math", "sqrt"),
    ("math", "cbrt"),
    ("math", "abs"),
    ("math", "floor"),
    ("math", "ceil"),
    ("math", "round"),
    ("math", "trunc"),
    ("math", "pow"),
    ("math", "log"),
    ("math", "log2"),
    ("math", "log10"),
    ("math", "exp"),
    ("math", "hypot"),
    ("math", "min"),
    ("math", "max"),
    ("math", "clamp"),
    ("math", "gcd"),
    ("math", "lcm"),
    ("math", "sign"),
    ("math", "mod"),
    ("math", "degrees"),
    ("math", "radians"),
    ("math", "is_integer"),
    ("math", "is_rational"),
    ("math", "range"),
    ("math", "divmod"),
    ("math", "pi"),
    ("math", "e"),
    ("math", "tau"),
    ("math", "inf"),
    ("math", "nan"),
    ("io", "read_file"),
    ("io", "write_file"),
    ("io", "append_file"),
    ("io", "read_bytes"),
    ("io", "write_bytes"),
    ("io", "write_line"),
    ("io", "eprint"),
    ("io", "read_line"),
    ("io", "exists"),
    ("io", "remove"),
    ("format", "format"),
    ("format", "join"),
    ("format", "format_num"),
    ("format", "pad"),
    ("format", "indent"),
    ("iter", "iter"),
    ("iter", "next"),
    ("iter", "to_list"),
    ("iter", "to_set"),
    ("iter", "enumerate"),
    ("iter", "chain"),
    ("iter", "map"),
    ("iter", "filter"),
    ("iter", "zip"),
    ("iter", "take"),
    ("iter", "skip"),
    ("iter", "drop"),
    ("iter", "fold"),
    ("iter", "count"),
    ("iter", "find"),
    ("iter", "any"),
    ("iter", "all"),
    ("iter", "repeat"),
    ("iter", "cycle"),
    ("dict", "keys"),
    ("dict", "values"),
    ("dict", "items"),
    ("dict", "get"),
    ("dict", "from_items"),
    ("dict", "from_list"),
    ("dict", "update"),
    ("dict", "merge"),
    ("dict", "invert"),
    ("dict", "setdefault"),
    ("ast", "parse"),
    ("ast", "unparse"),
    ("ast", "walk"),
    ("ast", "ast_clone"),
    ("ast", "ast_type_convert"),
    ("ast", "ast_call"),
    ("ast", "ast_macro_call"),
    ("ast", "ast_vec_push"),
    ("ast", "ast_vec_extend"),
    ("decos", "log"),
    ("decos", "once"),
    ("decos", "memoize"),
    ("decos", "timer"),
    ("decos", "debug"),
    ("decos", "retry"),
    ("decos", "validate"),
    ("decos", "catch"),
    ("decos", "deprecated"),
    ("decos", "trace"),
    ("decos", "singleton"),
    ("typing", "Union"),
    ("typing", "Maybe"),
    ("typing", "Optional"),
    ("typing", "Tuple"),
    ("typing", "Callable"),
    ("typing", "Never"),
    ("typing", "Literal"),
    ("typing", "fields_of"),
    ("typing", "protocol_of"),
    ("typing", "isinstanceof"),
    ("functional", "map"),
    ("functional", "filter"),
    ("functional", "zip"),
    ("functional", "reduce"),
    ("functional", "compose"),
    ("functional", "partial"),
    ("collections", "sorted"),
    ("collections", "reversed"),
    ("collections", "min"),
    ("collections", "max"),
    ("collections", "sum"),
    ("collections", "unique"),
    ("time", "now"),
    ("time", "now_ms"),
    ("time", "sleep"),
    ("time", "sleep_ms"),
    ("sync", "Channel"),
    ("sync", "Mutex"),
    ("sync", "WaitGroup"),
    ("sync", "Semaphore"),
    ("async", "gather"),
    ("async", "race"),
    ("async", "par_map"),
    ("async", "taskgroup"),
    ("text", "upper"),
    ("text", "lower"),
    ("text", "strip"),
    ("text", "split"),
    ("text", "contains"),
    ("text", "replace"),
    ("text", "join"),
    ("text", "from_bytes"),
    ("path", "join"),
    ("path", "basename"),
    ("path", "dirname"),
    ("path", "abspath"),
    ("fs", "exists"),
    ("fs", "is_file"),
    ("fs", "is_dir"),
    ("fs", "list_dir"),
    ("fs", "read_text"),
    ("fs", "write_text"),
    ("fs", "mkdir"),
    ("fs", "remove"),
    ("os", "getenv"),
    ("os", "setenv"),
    ("os", "args"),
    ("os", "cwd"),
    ("os", "run"),
    ("os", "capture"),
    ("json", "parse"),
    ("json", "stringify"),
    ("json", "parse_file"),
    ("json", "dump"),
    ("test", "assert_eq"),
    ("test", "assert_true"),
    ("test", "assert_raises"),
    ("debug", "traceback"),
    ("debug", "breakpoint"),
    ("random", "randint"),
    ("random", "random"),
    ("random", "choice"),
    ("random", "shuffle"),
    ("re", "compile"),
    ("re", "match"),
    ("re", "findall"),
    ("re", "sub"),
    ("re", "split"),
    ("hash", "md5"),
    ("hash", "sha256"),
    ("hash", "sha512"),
    ("hash", "hmac"),
    ("exceptions", "bases"),
    ("exceptions", "chain"),
    ("language", "C"),
    ("http", "get"),
    ("http", "post"),
    ("http", "put"),
    ("http", "delete"),
    ("http", "patch"),
    ("http", "head"),
    ("http", "request"),
    ("http", "serve"),
    ("http", "serve_tls"),
    ("log", "debug"),
    ("log", "info"),
    ("log", "warn"),
    ("log", "error"),
    ("log", "set_level"),
    ("log", "get_level"),
    ("net", "listen"),
    ("net", "listen_tls"),
    ("net", "bind_udp"),
    ("net", "ws_connect"),
    ("net", "ws_connect_tls"),
    ("net", "ws_accept"),
    ("net", "connect"),
    ("net", "connect_tls"),
    ("sqlite", "open"),
    ("encoding", "base64_encode"),
    ("encoding", "base64_decode"),
    ("encoding", "hex_encode"),
    ("encoding", "hex_decode"),
    ("encoding", "url_encode"),
    ("encoding", "url_decode"),
    ("encoding", "gzip_encode"),
    ("encoding", "gzip_decode"),
    ("csv", "parse"),
    ("csv", "stringify"),
    ("toml", "parse"),
    ("toml", "stringify"),
    ("yaml", "parse"),
    ("yaml", "stringify"),
    ("xml", "parse"),
    ("xml", "stringify"),
];

/// 常见 `std.*` 调用签名，供参数提示使用。名字必须与运行时导出一致。
pub const STD_SIGS: &[(&str, &str, &str)] = &[
    ("math", "sin", "std.math.sin(x)"),
    ("math", "cos", "std.math.cos(x)"),
    ("math", "tan", "std.math.tan(x)"),
    ("math", "asin", "std.math.asin(x)"),
    ("math", "acos", "std.math.acos(x)"),
    ("math", "atan", "std.math.atan(x)"),
    ("math", "atan2", "std.math.atan2(y, x)"),
    ("math", "sinh", "std.math.sinh(x)"),
    ("math", "cosh", "std.math.cosh(x)"),
    ("math", "tanh", "std.math.tanh(x)"),
    ("math", "sqrt", "std.math.sqrt(x)"),
    ("math", "cbrt", "std.math.cbrt(x)"),
    ("math", "abs", "std.math.abs(x)"),
    ("math", "floor", "std.math.floor(x)"),
    ("math", "ceil", "std.math.ceil(x)"),
    ("math", "round", "std.math.round(x)"),
    ("math", "trunc", "std.math.trunc(x)"),
    ("math", "pow", "std.math.pow(x, exp)"),
    ("math", "log", "std.math.log(x)"),
    ("math", "log2", "std.math.log2(x)"),
    ("math", "log10", "std.math.log10(x)"),
    ("math", "exp", "std.math.exp(x)"),
    ("math", "hypot", "std.math.hypot(a, b)"),
    ("math", "min", "std.math.min(a, b)"),
    ("math", "max", "std.math.max(a, b)"),
    ("math", "clamp", "std.math.clamp(x, lo, hi)"),
    ("math", "gcd", "std.math.gcd(a, b)"),
    ("math", "lcm", "std.math.lcm(a, b)"),
    ("math", "sign", "std.math.sign(x)"),
    ("math", "mod", "std.math.mod(a, b)"),
    ("math", "degrees", "std.math.degrees(x)"),
    ("math", "radians", "std.math.radians(x)"),
    ("math", "range", "std.math.range(start, end, step?)"),
    ("math", "divmod", "std.math.divmod(a, b)"),
    ("io", "read_file", "std.io.read_file(path)"),
    ("io", "write_file", "std.io.write_file(path, text)"),
    ("io", "append_file", "std.io.append_file(path, text)"),
    ("io", "read_bytes", "std.io.read_bytes(path)"),
    ("io", "write_bytes", "std.io.write_bytes(path, data)"),
    ("format", "format", "std.format.format(fmt, *args)"),
    ("format", "join", "std.format.join(sep, parts)"),
    ("json", "parse", "std.json.parse(text)"),
    ("json", "stringify", "std.json.stringify(value)"),
    ("http", "get", "std.http.get(url, opts?)"),
    ("http", "post", "std.http.post(url, body, opts?)"),
    ("http", "put", "std.http.put(url, body, opts?)"),
    ("http", "delete", "std.http.delete(url, opts?)"),
    ("http", "patch", "std.http.patch(url, body, opts?)"),
    ("http", "head", "std.http.head(url, opts?)"),
    ("http", "request", "std.http.request(method, url, opts?)"),
    ("http", "serve", "std.http.serve(port, handler)"),
    (
        "http",
        "serve_tls",
        "std.http.serve_tls(port, handler, cert, key)",
    ),
    ("log", "debug", "std.log.debug(...)"),
    ("log", "info", "std.log.info(...)"),
    ("log", "warn", "std.log.warn(...)"),
    ("log", "error", "std.log.error(...)"),
    ("log", "set_level", "std.log.set_level(name)"),
    ("log", "get_level", "std.log.get_level()"),
    ("net", "listen", "std.net.listen(port)"),
    ("net", "listen_tls", "std.net.listen_tls(port, cert, key)"),
    ("net", "bind_udp", "std.net.bind_udp(port)"),
    ("net", "ws_connect", "std.net.ws_connect(host, port, path?)"),
    (
        "net",
        "ws_connect_tls",
        "std.net.ws_connect_tls(host, port, path?)",
    ),
    ("net", "ws_accept", "std.net.ws_accept(conn)"),
    ("net", "connect", "std.net.connect(host, port)"),
    ("net", "connect_tls", "std.net.connect_tls(host, port)"),
    ("sqlite", "open", "std.sqlite.open(path)"),
    ("fs", "read_text", "std.fs.read_text(path)"),
    ("fs", "write_text", "std.fs.write_text(path, text)"),
    ("fs", "exists", "std.fs.exists(path)"),
    ("fs", "list_dir", "std.fs.list_dir(path)"),
    ("path", "join", "std.path.join(*parts)"),
    ("os", "getenv", "std.os.getenv(name)"),
    ("os", "setenv", "std.os.setenv(name, value)"),
    ("time", "sleep", "std.time.sleep(seconds)"),
    ("text", "split", "std.text.split(s, sep)"),
    ("text", "replace", "std.text.replace(s, old, new)"),
    ("re", "match", "std.re.match(pattern, text)"),
    (
        "encoding",
        "base64_encode",
        "std.encoding.base64_encode(data)",
    ),
    (
        "encoding",
        "base64_decode",
        "std.encoding.base64_decode(text)",
    ),
    ("encoding", "gzip_encode", "std.encoding.gzip_encode(data)"),
    ("encoding", "gzip_decode", "std.encoding.gzip_decode(data)"),
    ("toml", "parse", "std.toml.parse(text)"),
    ("toml", "stringify", "std.toml.stringify(value)"),
    ("yaml", "parse", "std.yaml.parse(text)"),
    ("yaml", "stringify", "std.yaml.stringify(value)"),
    ("csv", "parse", "std.csv.parse(text)"),
    ("csv", "stringify", "std.csv.stringify(rows)"),
    ("xml", "parse", "std.xml.parse(text)"),
    ("xml", "stringify", "std.xml.stringify(doc)"),
];

/// `std.sqlite.open` / `std.net.*` 返回句柄上的方法。
pub const HANDLE_MEMBERS: &[(&str, &[(&str, &str)])] = &[
    (
        "SqliteDb",
        &[
            ("execute", "execute(sql, params?)"),
            ("query", "query(sql, params?)"),
            ("close", "close()"),
        ],
    ),
    (
        "Listener",
        &[
            ("accept", "accept()"),
            ("addr", "addr()"),
            ("close", "close()"),
        ],
    ),
    (
        "Conn",
        &[
            ("read", "read(n?)"),
            ("write", "write(data)"),
            ("peer", "peer()"),
            ("close", "close()"),
        ],
    ),
    (
        "UdpSock",
        &[
            ("send_to", "send_to(data, host, port)"),
            ("recv_from", "recv_from()"),
            ("addr", "addr()"),
            ("close", "close()"),
        ],
    ),
    (
        "Ws",
        &[
            ("send", "send(data)"),
            ("recv", "recv()"),
            ("close", "close()"),
        ],
    ),
];

pub fn std_export_sig(module: &str, name: &str) -> Option<String> {
    if let Some((_, _, s)) = STD_SIGS.iter().find(|(m, n, _)| *m == module && *n == name) {
        return Some((*s).to_string());
    }
    if STD_EXPORTS.iter().any(|(m, n)| *m == module && *n == name) {
        return Some(format!("std.{module}.{name}(...)"));
    }
    None
}

pub fn std_export_doc(module: &str, name: &str) -> String {
    std_export_sig(module, name).unwrap_or_else(|| format!("std.{module}.{name}"))
}

pub fn handle_members(ty: &str) -> &'static [(&'static str, &'static str)] {
    HANDLE_MEMBERS
        .iter()
        .find(|(n, _)| *n == ty)
        .map(|(_, m)| *m)
        .unwrap_or(&[])
}

pub fn handle_member_sig(ty: &str, method: &str) -> Option<&'static str> {
    handle_members(ty)
        .iter()
        .find(|(n, _)| *n == method)
        .map(|(_, s)| *s)
}

/// `std.sqlite.open` → `SqliteDb` 等调用结果类型名。
pub fn std_call_type(path: &str) -> Option<&'static str> {
    match path {
        "std.sqlite.open" => Some("SqliteDb"),
        "std.net.listen" | "std.net.listen_tls" => Some("Listener"),
        "std.net.connect" | "std.net.connect_tls" => Some("Conn"),
        "std.net.bind_udp" => Some("UdpSock"),
        "std.net.ws_connect" | "std.net.ws_connect_tls" | "std.net.ws_accept" => Some("Ws"),
        _ => None,
    }
}

pub fn handle_method_result(ty: &str, method: &str) -> Option<&'static str> {
    match (ty, method) {
        ("Listener", "accept") => Some("Conn"),
        _ => None,
    }
}

pub fn std_module_doc(module: &str) -> String {
    format!("std.{module} — standard library submodule")
}

pub struct Snippet {
    pub label: &'static str,
    pub insert: &'static str,
    pub detail: &'static str,
}

pub const SNIPPETS: &[Snippet] = &[
    Snippet {
        label: "func",
        insert: "func ${1:name}($2) {\n    $0\n}",
        detail: "function",
    },
    Snippet {
        label: "struct",
        insert: "struct ${1:Name} {\n    $0\n}",
        detail: "struct",
    },
    Snippet {
        label: "if",
        insert: "if ($1) {\n    $0\n}",
        detail: "if block",
    },
    Snippet {
        label: "for",
        insert: "for (${1:x} in $2) {\n    $0\n}",
        detail: "for loop",
    },
    Snippet {
        label: "match",
        insert: "match $1 {\n    case $2 {\n        $0\n    }\n}",
        detail: "match",
    },
    Snippet {
        label: "try",
        insert: "try {\n    $1\n} catch ${2:e} {\n    $0\n}",
        detail: "try/catch",
    },
];
