//! 公开 runtime API 元数据 registry。
//!
//! LSP 补全、签名和静态 arity 检查只从这里读取；运行时双向同步测试保证
//! 所有公开全局内建与 `std` 导出都在 registry 中且没有幽灵条目。

pub const BUILTINS: &[(&str, &str)] = &[
    ("true", "bool true"),
    ("false", "bool false"),
    ("none", "empty value"),
    ("print", "print(...)"),
    ("len", "len(x)"),
    ("str", "str(x)"),
    ("repr", "repr(x)"),
    ("eval", "eval(ast)"),
    ("quote", "quote(hygienic_names, bindings, body)"),
    ("ast_struct", "ast_struct(ast)"),
    ("type", "type(x)"),
    ("convert", "convert(x, T)"),
    ("is_a", "is_a(x, T)"),
    ("isinstanceof", "isinstanceof(x, T)"),
    ("hash", "hash(x)"),
    ("copy", "copy(x)"),
    ("deepcopy", "deepcopy(x)"),
    ("id", "id(x)"),
    ("iter", "iter(xs)"),
    ("next", "next(it)"),
    ("input", "input([prompt])"),
    ("int", "int(x)"),
    ("dict", "dict(...)"),
    ("rational", "rational(n, d)"),
    ("floatstring", "floatstring(n)"),
    ("now", "now()"),
    ("gc", "gc()"),
    ("exit", "exit([code])"),
    ("help", "help(x)"),
    ("extern", "extern(...)"),
    ("std", "standard library"),
];

pub const STD_MODULES: &[&str] = &[
    "math",
    "io",
    "format",
    "iter",
    "dict",
    "ast",
    "decos",
    "typing",
    "functional",
    "collections",
    "time",
    "sync",
    "async",
    "text",
    "path",
    "fs",
    "os",
    "json",
    "test",
    "debug",
    "random",
    "re",
    "hash",
    "exceptions",
    "language",
    "http",
    "log",
    "net",
    "sqlite",
    "encoding",
    "csv",
    "toml",
    "yaml",
    "xml",
];

/// `(module, export)`。`module == ""` 表示 `std` 根上的名字。
pub const STD_EXPORTS: &[(&str, &str)] = &[
    ("", "concat"),
    ("math", "sin"),
    ("math", "cos"),
    ("math", "tan"),
    ("math", "asin"),
    ("math", "acos"),
    ("math", "atan"),
    ("math", "atan2"),
    ("math", "sinh"),
    ("math", "cosh"),
    ("math", "tanh"),
    ("math", "sqrt"),
    ("math", "cbrt"),
    ("math", "abs"),
    ("math", "floor"),
    ("math", "ceil"),
    ("math", "round"),
    ("math", "trunc"),
    ("math", "pow"),
    ("math", "log"),
    ("math", "log2"),
    ("math", "log10"),
    ("math", "exp"),
    ("math", "hypot"),
    ("math", "min"),
    ("math", "max"),
    ("math", "clamp"),
    ("math", "gcd"),
    ("math", "lcm"),
    ("math", "sign"),
    ("math", "mod"),
    ("math", "degrees"),
    ("math", "radians"),
    ("math", "is_integer"),
    ("math", "is_rational"),
    ("math", "range"),
    ("math", "divmod"),
    ("math", "pi"),
    ("math", "e"),
    ("math", "tau"),
    ("math", "inf"),
    ("math", "-inf"),
    ("math", "nan"),
    ("io", "read_file"),
    ("io", "write_file"),
    ("io", "append_file"),
    ("io", "read_bytes"),
    ("io", "write_bytes"),
    ("io", "write_line"),
    ("io", "eprint"),
    ("io", "read_line"),
    ("io", "exists"),
    ("io", "remove"),
    ("format", "format"),
    ("format", "join"),
    ("format", "format_num"),
    ("format", "pad"),
    ("format", "indent"),
    ("iter", "iter"),
    ("iter", "next"),
    ("iter", "to_list"),
    ("iter", "to_set"),
    ("iter", "enumerate"),
    ("iter", "chain"),
    ("iter", "map"),
    ("iter", "filter"),
    ("iter", "zip"),
    ("iter", "take"),
    ("iter", "skip"),
    ("iter", "drop"),
    ("iter", "fold"),
    ("iter", "count"),
    ("iter", "find"),
    ("iter", "any"),
    ("iter", "all"),
    ("iter", "repeat"),
    ("iter", "cycle"),
    ("dict", "keys"),
    ("dict", "values"),
    ("dict", "items"),
    ("dict", "get"),
    ("dict", "from_items"),
    ("dict", "from_list"),
    ("dict", "update"),
    ("dict", "merge"),
    ("dict", "invert"),
    ("dict", "setdefault"),
    ("ast", "parse"),
    ("ast", "unparse"),
    ("ast", "walk"),
    ("ast", "ast_clone"),
    ("ast", "ast_type_convert"),
    ("ast", "ast_call"),
    ("ast", "ast_macro_call"),
    ("ast", "ast_vec_push"),
    ("ast", "ast_vec_extend"),
    ("decos", "log"),
    ("decos", "once"),
    ("decos", "memoize"),
    ("decos", "timer"),
    ("decos", "debug"),
    ("decos", "retry"),
    ("decos", "validate"),
    ("decos", "catch"),
    ("decos", "deprecated"),
    ("decos", "trace"),
    ("decos", "singleton"),
    ("typing", "Union"),
    ("typing", "Maybe"),
    ("typing", "Optional"),
    ("typing", "Tuple"),
    ("typing", "Callable"),
    ("typing", "Covariant"),
    ("typing", "Contravariant"),
    ("typing", "Invariant"),
    ("typing", "Never"),
    ("typing", "Literal"),
    ("typing", "fields_of"),
    ("typing", "protocol_of"),
    ("typing", "isinstanceof"),
    ("functional", "map"),
    ("functional", "filter"),
    ("functional", "zip"),
    ("functional", "reduce"),
    ("functional", "compose"),
    ("functional", "partial"),
    ("functional", "identity"),
    ("functional", "const"),
    ("functional", "flip"),
    ("collections", "sorted"),
    ("collections", "reversed"),
    ("collections", "min"),
    ("collections", "max"),
    ("collections", "sum"),
    ("collections", "all"),
    ("collections", "any"),
    ("collections", "unique"),
    ("collections", "first"),
    ("collections", "last"),
    ("collections", "nth"),
    ("collections", "flatten"),
    ("collections", "chunk"),
    ("collections", "count"),
    ("collections", "group_by"),
    ("time", "now"),
    ("time", "now_ms"),
    ("time", "monotonic"),
    ("time", "sleep"),
    ("time", "sleep_ms"),
    ("time", "format"),
    ("time", "parse"),
    ("time", "utc_parts"),
    ("time", "parts"),
    ("time", "local_offset"),
    ("sync", "Channel"),
    ("sync", "Mutex"),
    ("sync", "RWMutex"),
    ("sync", "RwLock"),
    ("sync", "WaitGroup"),
    ("sync", "Semaphore"),
    ("sync", "Once"),
    ("sync", "Barrier"),
    ("sync", "Cond"),
    ("sync", "Atomic"),
    ("sync", "yield"),
    ("async", "gather"),
    ("async", "race"),
    ("async", "par_map"),
    ("async", "par_each"),
    ("async", "taskgroup"),
    ("async", "with_timeout"),
    ("async", "workers"),
    ("async", "Stream"),
    ("async", "stream"),
    ("async", "stream_of"),
    ("async", "stream_from_gen"),
    ("async", "stream_map"),
    ("async", "stream_filter"),
    ("async", "stream_take"),
    ("text", "Text"),
    ("text", "Bytes"),
    ("text", "Builder"),
    ("text", "upper"),
    ("text", "lower"),
    ("text", "strip"),
    ("text", "split"),
    ("text", "contains"),
    ("text", "replace"),
    ("text", "join"),
    ("text", "from_bytes"),
    ("text", "len"),
    ("text", "byte_len"),
    ("text", "is_empty"),
    ("text", "trim"),
    ("text", "trim_start"),
    ("text", "trim_end"),
    ("text", "lstrip"),
    ("text", "rstrip"),
    ("text", "split_ws"),
    ("text", "split_once"),
    ("text", "rsplit_once"),
    ("text", "rsplit"),
    ("text", "lines"),
    ("text", "chars"),
    ("text", "codepoints"),
    ("text", "from_chars"),
    ("text", "from_codepoints"),
    ("text", "to_bytes"),
    ("text", "ord"),
    ("text", "chr"),
    ("text", "startswith"),
    ("text", "endswith"),
    ("text", "find"),
    ("text", "rfind"),
    ("text", "count"),
    ("text", "replace_n"),
    ("text", "removeprefix"),
    ("text", "removesuffix"),
    ("text", "substring"),
    ("text", "slice"),
    ("text", "repeat"),
    ("text", "reverse"),
    ("text", "capitalize"),
    ("text", "title"),
    ("text", "swapcase"),
    ("text", "center"),
    ("text", "ljust"),
    ("text", "rjust"),
    ("text", "zfill"),
    ("text", "partition"),
    ("text", "rpartition"),
    ("text", "cmp"),
    ("text", "is_alpha"),
    ("text", "is_alnum"),
    ("text", "is_digit"),
    ("text", "is_space"),
    ("text", "is_lower"),
    ("text", "is_upper"),
    ("text", "is_ascii"),
    ("path", "join"),
    ("path", "basename"),
    ("path", "dirname"),
    ("path", "extension"),
    ("path", "stem"),
    ("path", "is_absolute"),
    ("path", "abspath"),
    ("path", "normalize"),
    ("path", "splitext"),
    ("fs", "exists"),
    ("fs", "is_file"),
    ("fs", "is_dir"),
    ("fs", "list_dir"),
    ("fs", "read_text"),
    ("fs", "write_text"),
    ("fs", "read_bytes"),
    ("fs", "write_bytes"),
    ("fs", "mkdir"),
    ("fs", "mkdir_all"),
    ("fs", "remove"),
    ("fs", "remove_dir"),
    ("fs", "rename"),
    ("fs", "copy"),
    ("os", "getenv"),
    ("os", "setenv"),
    ("os", "args"),
    ("os", "cwd"),
    ("os", "chdir"),
    ("os", "name"),
    ("os", "exit"),
    ("os", "run"),
    ("os", "capture"),
    ("json", "parse"),
    ("json", "stringify"),
    ("json", "parse_file"),
    ("json", "dump"),
    ("test", "assert_eq"),
    ("test", "assert_true"),
    ("test", "assert_raises"),
    ("test", "each"),
    ("test", "tmp_dir"),
    ("debug", "traceback"),
    ("debug", "format_tb"),
    ("debug", "print_tb"),
    ("debug", "format_exception"),
    ("debug", "type_name"),
    ("debug", "breakpoint"),
    ("random", "randint"),
    ("random", "random"),
    ("random", "randstring"),
    ("random", "choice"),
    ("random", "shuffle"),
    ("random", "sample"),
    ("random", "seed"),
    ("re", "compile"),
    ("re", "match"),
    ("re", "findall"),
    ("re", "sub"),
    ("re", "split"),
    ("hash", "md5"),
    ("hash", "sha256"),
    ("hash", "sha512"),
    ("hash", "hmac"),
    ("exceptions", "bases"),
    ("exceptions", "chain"),
    ("exceptions", "tree"),
    ("language", "C"),
    ("http", "get"),
    ("http", "post"),
    ("http", "put"),
    ("http", "delete"),
    ("http", "patch"),
    ("http", "head"),
    ("http", "request"),
    ("http", "serve"),
    ("http", "serve_tls"),
    ("log", "debug"),
    ("log", "info"),
    ("log", "warn"),
    ("log", "error"),
    ("log", "set_level"),
    ("log", "get_level"),
    ("net", "listen"),
    ("net", "listen_tls"),
    ("net", "bind_udp"),
    ("net", "ws_connect"),
    ("net", "ws_connect_tls"),
    ("net", "ws_accept"),
    ("net", "connect"),
    ("net", "connect_tls"),
    ("sqlite", "open"),
    ("encoding", "base64_encode"),
    ("encoding", "base64_decode"),
    ("encoding", "hex_encode"),
    ("encoding", "hex_decode"),
    ("encoding", "url_encode"),
    ("encoding", "url_decode"),
    ("encoding", "gzip_encode"),
    ("encoding", "gzip_decode"),
    ("csv", "parse"),
    ("csv", "stringify"),
    ("toml", "parse"),
    ("toml", "stringify"),
    ("yaml", "parse"),
    ("yaml", "stringify"),
    ("xml", "parse"),
    ("xml", "stringify"),
];

/// 常见 `std.*` 调用签名，供参数提示使用。名字必须与运行时导出一致。
pub const STD_SIGS: &[(&str, &str, &str)] = &[
    ("", "concat", "std.concat(...)"),
    ("math", "sin", "std.math.sin(x)"),
    ("math", "cos", "std.math.cos(x)"),
    ("math", "tan", "std.math.tan(x)"),
    ("math", "asin", "std.math.asin(x)"),
    ("math", "acos", "std.math.acos(x)"),
    ("math", "atan", "std.math.atan(x)"),
    ("math", "atan2", "std.math.atan2(y, x)"),
    ("math", "sinh", "std.math.sinh(x)"),
    ("math", "cosh", "std.math.cosh(x)"),
    ("math", "tanh", "std.math.tanh(x)"),
    ("math", "sqrt", "std.math.sqrt(x)"),
    ("math", "cbrt", "std.math.cbrt(x)"),
    ("math", "abs", "std.math.abs(x)"),
    ("math", "floor", "std.math.floor(x)"),
    ("math", "ceil", "std.math.ceil(x)"),
    ("math", "round", "std.math.round(x)"),
    ("math", "trunc", "std.math.trunc(x)"),
    ("math", "pow", "std.math.pow(x, exp)"),
    ("math", "log", "std.math.log(x)"),
    ("math", "log2", "std.math.log2(x)"),
    ("math", "log10", "std.math.log10(x)"),
    ("math", "exp", "std.math.exp(x)"),
    ("math", "hypot", "std.math.hypot(a, b)"),
    ("math", "min", "std.math.min(value, *values)"),
    ("math", "max", "std.math.max(value, *values)"),
    ("math", "clamp", "std.math.clamp(x, lo, hi)"),
    ("math", "gcd", "std.math.gcd(a, b)"),
    ("math", "lcm", "std.math.lcm(a, b)"),
    ("math", "sign", "std.math.sign(x)"),
    ("math", "mod", "std.math.mod(a, b)"),
    ("math", "degrees", "std.math.degrees(x)"),
    ("math", "radians", "std.math.radians(x)"),
    ("math", "range", "std.math.range(start, end, step?)"),
    ("math", "divmod", "std.math.divmod(a, b)"),
    ("io", "read_file", "std.io.read_file(path)"),
    ("io", "write_file", "std.io.write_file(path, text)"),
    ("io", "append_file", "std.io.append_file(path, text)"),
    ("io", "read_bytes", "std.io.read_bytes(path)"),
    ("io", "write_bytes", "std.io.write_bytes(path, data)"),
    ("format", "format", "std.format.format(fmt, *args)"),
    ("format", "join", "std.format.join(sep, parts)"),
    ("json", "parse", "std.json.parse(text)"),
    ("json", "stringify", "std.json.stringify(value)"),
    ("http", "get", "std.http.get(url, opts?)"),
    ("http", "post", "std.http.post(url, body, opts?)"),
    ("http", "put", "std.http.put(url, body, opts?)"),
    ("http", "delete", "std.http.delete(url, opts?)"),
    ("http", "patch", "std.http.patch(url, body, opts?)"),
    ("http", "head", "std.http.head(url, opts?)"),
    ("http", "request", "std.http.request(method, url, opts?)"),
    ("http", "serve", "std.http.serve(port, handler)"),
    (
        "http",
        "serve_tls",
        "std.http.serve_tls(port, handler, cert, key)",
    ),
    ("log", "debug", "std.log.debug(...)"),
    ("log", "info", "std.log.info(...)"),
    ("log", "warn", "std.log.warn(...)"),
    ("log", "error", "std.log.error(...)"),
    ("log", "set_level", "std.log.set_level(name)"),
    ("log", "get_level", "std.log.get_level()"),
    ("net", "listen", "std.net.listen(port)"),
    ("net", "listen_tls", "std.net.listen_tls(port, cert, key)"),
    ("net", "bind_udp", "std.net.bind_udp(port)"),
    ("net", "ws_connect", "std.net.ws_connect(host, port, path?)"),
    (
        "net",
        "ws_connect_tls",
        "std.net.ws_connect_tls(host, port, path?)",
    ),
    ("net", "ws_accept", "std.net.ws_accept(conn)"),
    ("net", "connect", "std.net.connect(host, port)"),
    ("net", "connect_tls", "std.net.connect_tls(host, port)"),
    ("sqlite", "open", "std.sqlite.open(path)"),
    ("fs", "read_text", "std.fs.read_text(path)"),
    ("fs", "write_text", "std.fs.write_text(path, text)"),
    ("fs", "read_bytes", "std.fs.read_bytes(path)"),
    ("fs", "write_bytes", "std.fs.write_bytes(path, data)"),
    ("fs", "exists", "std.fs.exists(path)"),
    ("fs", "is_file", "std.fs.is_file(path)"),
    ("fs", "is_dir", "std.fs.is_dir(path)"),
    ("fs", "list_dir", "std.fs.list_dir(path)"),
    ("fs", "mkdir", "std.fs.mkdir(path)"),
    ("fs", "mkdir_all", "std.fs.mkdir_all(path)"),
    ("fs", "remove", "std.fs.remove(path)"),
    ("fs", "remove_dir", "std.fs.remove_dir(path)"),
    ("fs", "rename", "std.fs.rename(from, to)"),
    ("fs", "copy", "std.fs.copy(from, to)"),
    ("path", "join", "std.path.join(*parts)"),
    ("os", "getenv", "std.os.getenv(name)"),
    ("os", "setenv", "std.os.setenv(name, value)"),
    ("os", "args", "std.os.args()"),
    ("os", "exit", "std.os.exit(code?)"),
    ("os", "cwd", "std.os.cwd()"),
    ("os", "chdir", "std.os.chdir(path)"),
    ("os", "name", "std.os.name()"),
    ("os", "run", "std.os.run(command, args?)"),
    ("os", "capture", "std.os.capture(command, args?)"),
    ("time", "sleep", "std.time.sleep(seconds)"),
    ("time", "sleep_ms", "std.time.sleep_ms(ms)"),
    ("time", "format", "std.time.format(secs, fmt, tz?)"),
    ("time", "parse", "std.time.parse(text, fmt, tz?)"),
    ("time", "utc_parts", "std.time.utc_parts(secs)"),
    ("time", "parts", "std.time.parts(secs, tz?)"),
    ("time", "local_offset", "std.time.local_offset()"),
    ("time", "now", "std.time.now()"),
    ("time", "now_ms", "std.time.now_ms()"),
    ("time", "monotonic", "std.time.monotonic()"),
    ("sync", "Channel", "std.sync.Channel(capacity?)"),
    ("sync", "Mutex", "std.sync.Mutex(value)"),
    ("sync", "RWMutex", "std.sync.RWMutex(value)"),
    ("sync", "RwLock", "std.sync.RwLock(value)"),
    ("sync", "WaitGroup", "std.sync.WaitGroup(count?)"),
    ("sync", "Semaphore", "std.sync.Semaphore(permits)"),
    ("sync", "Once", "std.sync.Once()"),
    ("sync", "Barrier", "std.sync.Barrier(parties)"),
    ("sync", "Cond", "std.sync.Cond()"),
    ("sync", "Atomic", "std.sync.Atomic(value)"),
    ("sync", "yield", "std.sync.yield()"),
    ("async", "taskgroup", "std.async.taskgroup()"),
    ("async", "with_timeout", "std.async.with_timeout(seconds)"),
    ("async", "gather", "std.async.gather(tasks)"),
    ("async", "race", "std.async.race(tasks)"),
    ("async", "par_map", "std.async.par_map(iterable, callable)"),
    (
        "async",
        "par_each",
        "std.async.par_each(iterable, callable)",
    ),
    ("async", "workers", "std.async.workers()"),
    ("async", "Stream", "std.async.Stream(capacity?)"),
    ("async", "stream", "std.async.stream(capacity?)"),
    ("async", "stream_of", "std.async.stream_of(iterable)"),
    (
        "async",
        "stream_from_gen",
        "std.async.stream_from_gen(generator)",
    ),
    (
        "async",
        "stream_map",
        "std.async.stream_map(stream, callable)",
    ),
    (
        "async",
        "stream_filter",
        "std.async.stream_filter(stream, predicate)",
    ),
    (
        "async",
        "stream_take",
        "std.async.stream_take(stream, count)",
    ),
    ("test", "each", "std.test.each(name, rows, fn)"),
    ("test", "tmp_dir", "std.test.tmp_dir()"),
    ("debug", "traceback", "std.debug.traceback()"),
    ("debug", "format_tb", "std.debug.format_tb(traceback)"),
    ("debug", "print_tb", "std.debug.print_tb(traceback)"),
    (
        "debug",
        "format_exception",
        "std.debug.format_exception(exception)",
    ),
    ("debug", "type_name", "std.debug.type_name(value)"),
    ("debug", "breakpoint", "std.debug.breakpoint()"),
    ("random", "randint", "std.random.randint(lo, hi)"),
    ("random", "random", "std.random.random()"),
    ("random", "randstring", "std.random.randstring(length?)"),
    ("random", "choice", "std.random.choice(iterable)"),
    ("random", "shuffle", "std.random.shuffle(list)"),
    ("random", "sample", "std.random.sample(iterable, count)"),
    ("random", "seed", "std.random.seed(value?)"),
    ("text", "split", "std.text.split(s, sep)"),
    ("text", "replace", "std.text.replace(s, old, new)"),
    ("re", "match", "std.re.match(pattern, text)"),
    (
        "encoding",
        "base64_encode",
        "std.encoding.base64_encode(data)",
    ),
    (
        "encoding",
        "base64_decode",
        "std.encoding.base64_decode(text)",
    ),
    ("encoding", "gzip_encode", "std.encoding.gzip_encode(data)"),
    ("encoding", "gzip_decode", "std.encoding.gzip_decode(data)"),
    ("toml", "parse", "std.toml.parse(text)"),
    ("toml", "stringify", "std.toml.stringify(value)"),
    ("yaml", "parse", "std.yaml.parse(text)"),
    ("yaml", "stringify", "std.yaml.stringify(value)"),
    ("csv", "parse", "std.csv.parse(text)"),
    ("csv", "stringify", "std.csv.stringify(rows)"),
    ("xml", "parse", "std.xml.parse(text)"),
    ("xml", "stringify", "std.xml.stringify(doc)"),
];

/// `std.sqlite.open` / `std.net.*` 返回句柄上的方法。
pub const HANDLE_MEMBERS: &[(&str, &[(&str, &str)])] = &[
    (
        "SqliteDb",
        &[
            ("execute", "execute(sql, params?)"),
            ("query", "query(sql, params?)"),
            ("close", "close()"),
        ],
    ),
    (
        "Listener",
        &[
            ("accept", "accept()"),
            ("addr", "addr()"),
            ("close", "close()"),
        ],
    ),
    (
        "Conn",
        &[
            ("read", "read(n?)"),
            ("write", "write(data)"),
            ("peer", "peer()"),
            ("close", "close()"),
        ],
    ),
    (
        "UdpSock",
        &[
            ("send_to", "send_to(data, host, port)"),
            ("recv_from", "recv_from()"),
            ("addr", "addr()"),
            ("close", "close()"),
        ],
    ),
    (
        "Ws",
        &[
            ("send", "send(data)"),
            ("recv", "recv()"),
            ("close", "close()"),
        ],
    ),
];

pub fn std_export_sig(module: &str, name: &str) -> Option<String> {
    if let Some((_, _, s)) = STD_SIGS.iter().find(|(m, n, _)| *m == module && *n == name) {
        return Some((*s).to_string());
    }
    if STD_EXPORTS.iter().any(|(m, n)| *m == module && *n == name) {
        return Some(if module.is_empty() {
            format!("std.{name}(...)")
        } else {
            format!("std.{module}.{name}(...)")
        });
    }
    None
}

pub fn std_export_doc(module: &str, name: &str) -> String {
    std_export_sig(module, name).unwrap_or_else(|| format!("std.{module}.{name}"))
}

pub fn handle_members(ty: &str) -> &'static [(&'static str, &'static str)] {
    HANDLE_MEMBERS
        .iter()
        .find(|(n, _)| *n == ty)
        .map(|(_, m)| *m)
        .unwrap_or(&[])
}

pub fn handle_member_sig(ty: &str, method: &str) -> Option<&'static str> {
    handle_members(ty)
        .iter()
        .find(|(n, _)| *n == method)
        .map(|(_, s)| *s)
}

/// `std.sqlite.open` → `SqliteDb` 等调用结果类型名。
pub fn std_call_type(path: &str) -> Option<&'static str> {
    match path {
        "std.sqlite.open" => Some("SqliteDb"),
        "std.net.listen" | "std.net.listen_tls" => Some("Listener"),
        "std.net.connect" | "std.net.connect_tls" => Some("Conn"),
        "std.net.bind_udp" => Some("UdpSock"),
        "std.net.ws_connect" | "std.net.ws_connect_tls" | "std.net.ws_accept" => Some("Ws"),
        _ => None,
    }
}

pub fn handle_method_result(ty: &str, method: &str) -> Option<&'static str> {
    match (ty, method) {
        ("Listener", "accept") => Some("Conn"),
        _ => None,
    }
}

pub fn std_module_doc(module: &str) -> String {
    format!("std.{module} — standard library submodule")
}

/// 全局内建的静态参数范围。非可调用值或未知动态入口返回 `None`。
pub fn builtin_arity(name: &str) -> Option<(usize, Option<usize>)> {
    let sig = BUILTINS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, sig)| *sig)?;
    parse_sig_arity(sig)
}

/// `std` 导出的静态参数范围。特殊范围和签名都属于本 registry。
pub fn std_arity(module: &str, export: &str) -> Option<(usize, Option<usize>)> {
    if let Some((_, _, min, max)) = STD_ARITY
        .iter()
        .find(|(m, e, _, _)| *m == module && *e == export)
    {
        return Some((*min, *max));
    }
    let sig = STD_SIGS
        .iter()
        .find(|(m, e, _)| *m == module && *e == export)
        .map(|(_, _, sig)| *sig)?;
    parse_sig_arity(sig)
}

/// 无法仅由展示签名表达的参数范围。`None` max 表示无上限。
const STD_ARITY: &[(&str, &str, usize, Option<usize>)] = &[
    ("math", "range", 1, Some(3)),
    ("math", "min", 1, None),
    ("math", "max", 1, None),
    ("net", "listen", 1, Some(2)),
    ("net", "listen_tls", 3, Some(4)),
    ("net", "bind_udp", 1, Some(2)),
    ("net", "ws_connect", 2, Some(3)),
    ("net", "ws_connect_tls", 2, Some(3)),
    ("http", "serve", 2, Some(3)),
    ("http", "serve_tls", 4, Some(5)),
    ("log", "debug", 0, None),
    ("log", "info", 0, None),
    ("log", "warn", 0, None),
    ("log", "error", 0, None),
    ("format", "format", 1, None),
    ("path", "join", 0, None),
    ("io", "write_line", 0, None),
    ("io", "eprint", 0, None),
    ("io", "read_line", 0, Some(1)),
    ("text", "split", 1, Some(3)),
    ("dict", "get", 2, Some(3)),
    ("dict", "merge", 0, None),
    ("time", "format", 2, Some(3)),
    ("time", "parse", 2, Some(3)),
    ("time", "parts", 1, Some(2)),
    ("time", "sleep", 0, Some(1)),
    ("time", "sleep_ms", 0, Some(1)),
];

fn parse_sig_arity(sig: &str) -> Option<(usize, Option<usize>)> {
    let start = sig.find('(')?;
    let end = sig.rfind(')')?;
    let inner = sig[start + 1..end].trim();
    if inner.is_empty() {
        return Some((0, Some(0)));
    }
    if inner == "..." || inner == "*args" {
        return Some((0, None));
    }
    let mut min = 0usize;
    let mut max = 0usize;
    let mut unbounded = false;
    for part in inner.split(',') {
        let p = part.trim();
        if p.is_empty() {
            continue;
        }
        if p == "..." || p.starts_with('*') {
            unbounded = true;
            continue;
        }
        max += 1;
        if !p.ends_with('?') && !p.ends_with("?]") && !p.contains('[') {
            min += 1;
        }
    }
    Some((min, if unbounded { None } else { Some(max) }))
}

pub struct Snippet {
    pub label: &'static str,
    pub insert: &'static str,
    pub detail: &'static str,
}

pub const SNIPPETS: &[Snippet] = &[
    Snippet {
        label: "func",
        insert: "func ${1:name}($2) {\n    $0\n}",
        detail: "function",
    },
    Snippet {
        label: "struct",
        insert: "struct ${1:Name} {\n    $0\n}",
        detail: "struct",
    },
    Snippet {
        label: "if",
        insert: "if ($1) {\n    $0\n}",
        detail: "if block",
    },
    Snippet {
        label: "for",
        insert: "for (${1:x} in $2) {\n    $0\n}",
        detail: "for loop",
    },
    Snippet {
        label: "match",
        insert: "match $1 {\n    case $2 {\n        $0\n    }\n}",
        detail: "match",
    },
    Snippet {
        label: "try",
        insert: "try {\n    $1\n} catch ${2:e} {\n    $0\n}",
        detail: "try/catch",
    },
];
